services:
  m-common:
    container_name: m-common
    image: ${ECR_REGISTRY}/m-common:latest
    build:
      context: ./m-common
      dockerfile: Dockerfile
    networks:
      - shared-net
    ports:
      - "19090:9090"
    environment:
      - JAVA_OPTS=-Xmx300m -Xms150m
      - IMAGE_NAME=${IMAGE_NAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.4'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  m-customer:
    container_name: m-customer
    image: ${ECR_REGISTRY}/m-customer:latest
    build:
      context: ./m-customer
      dockerfile: Dockerfile
    networks:
      - shared-net
    ports:
      - "19091:9091"
    environment:
      - JAVA_OPTS=-Xmx300m -Xms150m
      - IMAGE_NAME=${IMAGE_NAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.4'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  m-manager:
    container_name: m-manager
    image: ${ECR_REGISTRY}/m-manager:latest
    build:
      context: ./m-manager
      dockerfile: Dockerfile
    networks:
      - shared-net
    ports:
      - "19092:9092"
    environment:
      - JAVA_OPTS=-Xmx300m -Xms150m
      - IMAGE_NAME=${IMAGE_NAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.4'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  m-admin:
    container_name: m-admin
    image: ${ECR_REGISTRY}/m-admin:latest
    build:
      context: ./m-admin
      dockerfile: Dockerfile
    networks:
      - shared-net
    ports:
      - "19093:9093"
    environment:
      - JAVA_OPTS=-Xmx300m -Xms150m
      - IMAGE_NAME=${IMAGE_NAME}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.4'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  antmen-db-data:
    driver: local
    name: server_antmen-db-data

networks:
  shared-net:
    external: true