spring:
  config:
    import: "classpath:application-common-${SPRING_PROFILES_ACTIVE:local}.yml"
    # import: "file:${PROJECT_ROOT_PATH}/KBE5_AntMen_BE/m-common/src/main/resources/application-common.yml"

server:
  port: 9090
