plugins {
    id 'java'
}

group = 'com.antmen'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':domain')
    implementation project(':common')
    
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 테스트
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // MySQL
    runtimeOnly 'com.mysql:mysql-connector-j'

    // QueryDSL (jakarta)
    implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'

    // S3
    implementation 'software.amazon.awssdk:s3:2.31.54'
    implementation 'software.amazon.awssdk:auth:2.31.54'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.apache.commons:commons-pool2'
}

// QueryDSL Q타입 생성 위치
def querydslDir = layout.buildDirectory.dir("generated/querydsl").get().asFile

sourceSets {
    main {
        java {
            srcDir querydslDir
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.annotationProcessorGeneratedSourcesDirectory = file(querydslDir)
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

jar {
    from {
        sourceSets.main.resources.srcDirs
    }
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}