# .github/workflows/build-check.yml
name: Build Check

on:
  pull_request:
    branches: ["**"]

# 권한 설정 추가
permissions:
  contents: read
  pull-requests: write # PR 코멘트 작성 권한
  issues: write # 이슈 작성 권한

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
          JAVA_OPTS: "-Xmx2048m"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images for ARM64 (No Push)
        run: |
          # Build all modules with multi-architecture support
          for module in m-admin m-common m-customer m-manager; do
            echo "Building $module for multi-architecture..."
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag test-$module:latest \
              -f $module/Dockerfile \
              ./$module/ \
              --load=false
          done

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build/reports/
          if-no-files-found: warn
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.pull_request.head.ref;
            const commit = context.sha;
            const commitUrl = `https://github.com/${owner}/${repo}/commit/${commit}`;

            let message = `❌ 멀티 아키텍처 빌드 실패 알림\n\n`;
            message += `브랜치: ${branch}\n`;
            message += `커밋: ${commitUrl}\n`;
            message += `작업자: ${context.actor}\n\n`;
            message += `테스트를 제외한 멀티 아키텍처 빌드가 실패했습니다.\n`;
            message += `빌드 대상: m-admin, m-common, m-customer, m-manager\n`;
            message += `플랫폼: linux/amd64, linux/arm64\n\n`;
            message += `자세한 내용은 GitHub Actions 로그를 확인해주세요.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: owner,
              repo: repo,
              body: message
            });

      - name: Notify on success
        if: success()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branch = context.payload.pull_request.head.ref;
            const commit = context.sha;
            const commitUrl = `https://github.com/${owner}/${repo}/commit/${commit}`;

            let message = `✅ 멀티 아키텍처 빌드 성공 알림\n\n`;
            message += `브랜치: ${branch}\n`;
            message += `커밋: ${commitUrl}\n`;
            message += `작업자: ${context.actor}\n\n`;
            message += `테스트를 제외한 멀티 아키텍처 빌드가 성공적으로 완료되었습니다.\n`;
            message += `빌드 대상: m-admin, m-common, m-customer, m-manager\n`;
            message += `플랫폼: linux/amd64, linux/arm64\n\n`;
            message += `이제 ARM64 환경(t4g 인스턴스)에서도 정상 작동합니다.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: owner,
              repo: repo,
              body: message
            });